language: cpp


before_install:
  - export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/openssl/include"
  - export LDFLAGS="$LDFLAGS -L/usr/local/opt/openssl/lib"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated openssl || brew upgrade openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink protobuf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql sqlite hiredis; fi

jobs:
  include:
  - name: ubuntu focal AMD64 C
    os: linux
    arch: amd64
    dist: focal
    sudo: required
    addons:
      apt:
        packages:
        - mysql-client
        - debhelper
        - dpkg-dev
        - libssl-dev
        - libevent-dev
        - sqlite3
        - libsqlite3-dev
        - postgresql-client
        - libpq-dev
        - libmysqlclient-dev
        - libhiredis-dev
  - name: ubuntu Focal AMD64 C++
    os: linux
    arch: amd64
    dist: focal
    sudo: required
    env:
    - CC=g++
    addons:
      apt:
        packages:
        - mysql-client
        - debhelper
        - dpkg-dev
        - libssl-dev
        - libevent-dev
        - sqlite3
        - libsqlite3-dev
        - postgresql-client
        - libpq-dev
        - libmysqlclient-dev
        - libhiredis-dev
  - os: linux
    arch: amd64
    dist: bionic
    sudo: required
    addons:
      apt:
        packages:
        - mysql-client
        - debhelper
        - dpkg-dev
        - libssl-dev
        - libevent-dev
        - sqlite3
        - libsqlite3-dev
        - postgresql-client
        - libpq-dev
        - libmysqlclient-dev
        - libhiredis-dev
  - os: linux
    arch: arm64
    dist: bionic
    sudo: required
    addons:
      apt:
        packages:
        - mysql-client
        - debhelper
        - dpkg-dev
        - libssl-dev
        - libevent-dev
        - sqlite3
        - libsqlite3-dev
        - postgresql-client
        - libpq-dev
        - libmysqlclient-dev
        - libhiredis-dev
  - os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - mysql-client-5.6
        - debhelper
        - dpkg-dev
        - libssl-dev
        - libevent-dev
        - sqlite3
        - libsqlite3-dev
        - postgresql-client
        - libpq-dev
        - libmysqlclient-dev
        - libhiredis-dev
  - os: osx
    osx_image: xcode11.3
 # - os: osx
 #   osx_image: xcode11.6
  - os: osx
    osx_image: xcode12
  - os: linux
    arch: ppc64le
    dist: xenial
    sudo: required
    addons:
      apt:
        packages:
        - mysql-client
        - debhelper
        - dpkg-dev
        - libssl-dev
        - libevent-dev
        - sqlite3
        - libsqlite3-dev
        - postgresql-client
        - libpq-dev
        - libmysqlclient-dev
        - libhiredis-dev
  - os: linux
    arch: ppc64le
    dist: bionic
    sudo: required
    addons:
      apt:
        packages:
        - mysql-client
        - debhelper
        - dpkg-dev
        - libssl-dev
        - libevent-dev
        - sqlite3
        - libsqlite3-dev
        - postgresql-client
        - libpq-dev
        - libmysqlclient-dev
        - libhiredis-dev

notifications:
  slack:
    secure: N12+BCGiTDzfKkYnjF+666ZhREuBncfPpWge9AdG6DwusyGza+hNrjfRRHjF8WfGQj+X8ogFoF1lVFDC27lwH1ElOv4GJHShnGbtsWv10Va1GdDafDeC5JorUNWHlsDHC1AZkNUj9n2KAZTSbN076gUaNhwsXob/B1MEnNKXibitDdyE2FC6wCRu6ckXM4UiEXoG/a7lHS4m9dKt2xDUNK8vwhtRdCkip9YW8rUFdiwqMScdr9OdF8YWiKJIUYV7LC7eXF0YqslWTJkeIMEEnvotLs4JNytFz1wNPzTiY8hM4nPM0YwC1oPhFWlBodQ1x+dBX3vxitnque0gVhj/p6Eij0amM3tirgONw/r2V9JToE6vfh6ERAWIVzI/+tmqcEbZZvwcgafZphlT9W/8Gzy/av/zTpdfaTUEYnsuQRCA87FPIFAAVjzSmT3llY6WQXFB+UU0T0ZE42PkPqhR3zpjqt7nDXf2g1ZY5ZRkWRvznyqBdrVx0Ld8AKnv/Ynk/KqiJqV94DUMhGzAadqbYrDL/87eiDtW4lBpCl7cQnfEI7besdduNzWlgmJ93CU1kyruK37/w+D1jyBnc1ppQTj1+B2GanB0weY7ViNqyQmN+tam7EmM+9R8VKMi8EO0xlvb1YFL18NtrCMMMEsZRHj823g68lFntUWs5oGsFMI=
  email:
    recipients:
       - misi@majd.eu
    # on_success: [always|never|change] # default: always
    # on_failure: [always|never|change] # default: always
