name: AmazonLinux2

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

# make GHA actions use node16 to use ancient container images
# See https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
# Unclear how long this will work though
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        # amazonlinux 2 is end-of-life 2025-06
        os: [ 'amazonlinux:2' ]

    runs-on: ubuntu-latest
    container: ${{ matrix.os }}

    steps:
    - name: Install Dependencies
      run: |
        yum install -y gcc make gzip tar openssl11-devel libevent-devel
    # Delay checkout until after dependencies have been installed. Amazon linux is very minimal and lacks basic stuff by default.
    # use v3 of checkout until the weird container, nodejs, glibc issue is fixed
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure
      run: ./configure

    - name: Compile
      run: make

    - name: Unit Test
      run: make check

    - name: Integration Test
      working-directory: examples
      run: ./run_tests.sh && ./run_tests_conf.sh && ./run_tests_prom.sh
